# Generated by Django 4.2 on 2026-07-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('assesment_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Graduated', 'Graduated')], default='Active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('date_admitted', models.DateField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='classes.classroom')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.parentprofile')),
            ],
        ),
    ]
