# Generated by Django 5.2.16 on 2026-07-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='assesment_number',
            new_name='assessment_number',
        ),
    ]
