# Generated by Django 5.2.16 on 2026-07-19 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classroom_unique_together_and_more'),
        ('students', '0003_alter_student_options_student_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='classes.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student')),
                ('to_classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='classes.classroom')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Transfer',
                'verbose_name_plural': 'Student Transfers',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
