# Generated by Django 4.2 on 2026-08-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studenttransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent',
            new_name='national_id',
        ),
    ]
