# Generated by Django 4.2 on 2026-08-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_parent_student_national_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='national_id',
            new_name='parent',
        ),
    ]
