# Generated by Django 4.2 on 2026-08-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role_studentprofile'),
        ('students', '0006_rename_national_id_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.parentprofile'),
        ),
    ]
