# Generated by Django 5.2.16 on 2026-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('grade', 'stream'), name='unique_grade_stream'),
        ),
    ]
