# Generated by Django 4.2 on 2026-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classroom_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='total_students',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
