# Generated by Django 4.2 on 2026-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classroom_total_students_alter_classroom_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.CharField(choices=[('Day Care', 'Day Care'), ('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=20),
        ),
    ]
