from django.urls import path
from .views import DashboardAPIView, DashboardFeeSummaryAPIView, ExamPerformanceDashboardAPIView, RecentAdmissionsAPIView, RecentFeePaymentsAPIView, TodayAttendanceSummaryAPIView, TopOutstandingStudentsAPIView, TopPerformingClassesAPIView, UpcomingNotificationsAPIView 

urlpatterns = [
      path(
        "",
        DashboardAPIView.as_view(),
        name="dashboard",
    ),
    path(
        "top-students/",
        TopOutstandingStudentsAPIView.as_view(),
        name="top-students",
    ),
    path(
        "top-classes/",
        TopPerformingClassesAPIView.as_view(),
        name="top-performing-classes",
    ),
    path(
        "recent-payments/",
        RecentFeePaymentsAPIView.as_view(),
        name="recent-fee-payments",
    ),
    path(
        "recent-admissions/",
        RecentAdmissionsAPIView.as_view(),
        name="recent-admissions",
    ),
    path(
        "attendance/today/",
        TodayAttendanceSummaryAPIView.as_view(),
        name="today-attendance-summary",
    ),
    path(
        "fees/summary/",
        DashboardFeeSummaryAPIView.as_view(),
        name="dashboard-fee-summary",
    ),
    path(
        "exam-performance/",
        ExamPerformanceDashboardAPIView.as_view(),
        name="exam-performance-dashboard",
    ),
    path(
        "notifications/",
        UpcomingNotificationsAPIView.as_view(),
        name="dashboard-notifications",
    ),
    path(
        "teacher/assessments/<int:pk>/",
        TeacherAssessmentDetailsAPIView.as_view(),
        name="teacher-assessment-details",
    )
    p
    path(
        "teacher/assessments/",
        TeacherAssessmentListAPIView.as_view(),
        name="teacher-assessment-list",
    ),
    path(
        "teacher/subjects/",
        TeacherSubjectsAPIView.as_view(),
        name="teacher-subjects",
    ),
    path(
        "teacher/classes/",
        TeacherClassesAPIView.as_view(),
        name="teacher-classes",
    ),
    path(
        "teacher/profile/",
        TeacherProfileAPIView.as_view(),
        name="teacher-profile",
    ),
    path(
        "teacher/assessment/<int:pk>/submit/",
        TeacherAssessmentSubmitAPIView.as_view(),
        name="teacher-assessment-submit",
    ),
    path(
        "teacher/assessment/<int:pk>/",
        TeacherAssessmentDetailsAPIView.as_view(),
        name="teacher-assessment-details",
    ),
    path(
        "student/profile/",
        StudentProfileAPIView.as_view(),
        name="student-profile",
    ),
    path(
        "student/subjects/",
        StudentSubjectsAPIView.as_view(),
        name="student-subjects",
    ),
    path(
        "student/attendance/",
        StudentAttendanceAPIView.as_view(),
        name="student-attendance",
    ),
    path(
        "student/fees/",
        StudentFeesAPIView.as_view(),
        name="student-fees",
    ),
    path(
        "student/assessments/",
        StudentAssessmentListAPIView.as_view(),
        name="student-assessment-list",
    ),
    path(
        "student/assessment/<int:pk>/",
        StudentAssessmentDetailsAPIView.as_view(),
        name="student-assessment-details",
    ),
    path(
        "student/results/",
        StudentResultsAPIView.as_view(),
        name="student-results",
    ),
    path(
        "student/result/<int:pk>/",
        StudentResultDetailsAPIView.as_view(),
        name="student-result-details",
    ),
    
]  