# Generated by Django 4.2 on 2026-08-07 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], default='SUPER_ADMIN', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['admission_number'],
            },
        ),
    ]
