# Generated by Django 4.2 on 2026-08-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent/Guardian phone number', max_length=20, null=True),
        ),
    ]
