# Generated by Django 4.2 on 2026-08-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentStudent',
        ),
    ]
