# Generated by Django 5.2.16 on 2026-07-18 14:47

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='academic_year',
            field=models.CharField(default=assignments.models.current_academic_year, max_length=9),
        ),
    ]
