# Generated by Django 4.2 on 2026-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_teacherassignment_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'academic_year', 'term'], name='assignments_teacher_c5a031_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['classroom', 'academic_year', 'term'], name='assignments_classro_96daf8_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['subject', 'academic_year', 'term'], name='assignments_subject_f2cf7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom', 'subject', 'academic_year', 'term'), name='unique_teacher_class_subject_term'),
        ),
    ]
