# Generated by Django 5.2.16 on 2026-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anouncements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('All Users', 'All Users'), ('Staff', 'Staff'), ('Parents', 'Parents'), ('Teachers', 'Teachers')], default='All Users', max_length=20),
        ),
    ]
