# Generated by Django 4.2 on 2026-08-08 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anouncements', '0002_alter_announcement_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
