# Generated by Django 4.2 on 2026-07-21 19:11

from django.db import migrations, models
import timetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timetable_options_timetable_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='academic_year',
            field=models.CharField(default=timetable.models.Timetable.current_academic_year, max_length=9),
        ),
    ]
