# Generated by Django 4.2 on 2026-07-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Attendance', 'Attendance'), ('Fees', 'Fees'), ('Results', 'Results'), ('Announcement', 'Announcement'), ('General', 'General')], max_length=40),
        ),
    ]
