# Generated by Django 4.2 on 2026-08-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesubmission_unique_together_and_more'),
        ('notifiations', '0002_notification_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.attendance'),
        ),
    ]
