# Generated by Django 5.2.16 on 2026-07-19 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['student__admission_number'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='attendancesubmission',
            options={'ordering': ['-date', 'classroom'], 'verbose_name': 'Attendance Submission', 'verbose_name_plural': 'Attendance Submissions'},
        ),
        migrations.AddField(
            model_name='attendancesubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancesubmission',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='attendancesubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
