# Generated by Django 4.2 on 2026-08-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_teacherassignment_academic_year'),
        ('attendance', '0002_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesubmission',
            name='assignment',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_submissions', to='assignments.teacherassignment'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendancesubmission',
            unique_together={('assignment', 'date')},
        ),
    ]
