# Generated by Django 4.2 on 2026-08-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesubmission',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='attendancesubmission',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='attendancesubmission',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendancesubmission',
            name='coordinator_comments',
        ),
        migrations.AddField(
            model_name='attendancesubmission',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=10),
        ),
    ]
